# Generated by Django 6.0.1 on 2026-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ejemplo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="ejemplos/")),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
