# Generated by Django 6.0.1 on 2026-02-13 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_ejemplo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ejemplo",
            name="tipo",
        ),
        migrations.AddField(
            model_name="ejemplo",
            name="producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ejemplos",
                to="tienda.producto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ejemplo",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Opcional: Breve descripción de este ejemplo",
                null=True,
            ),
        ),
    ]
